name: Test Adapters Against Schema

on:
  push:
    branches:
      - main
      - schema

  pull_request:
    branches: "main"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file:
          - test/test_nodes.py
          # - test/test_edges.py
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi # Skip dev dependencies if not needed

      - name: Set environment variables
        run: |
          echo "ADAPTERS_CONFIG=./config/adapters_config_sample.yaml" >> $GITHUB_ENV
          echo "DBSNP_RSIDS=./aux_files/sample_dbsnp_rsids.pkl" >> $GITHUB_ENV
          echo "DBSNP_POS=./aux_files/sample_dbsnp_pos.pkl" >> $GITHUB_ENV

      - name: Run tests
        run: |
          poetry run pytest -n auto ${{ matrix.test_file }} --adapters-config=$ADAPTERS_CONFIG --dbsnp-rsids=$DBSNP_RSIDS --dbsnp-pos=$DBSNP_POS -vv -s
